version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  simple:
    format: "%(levelname)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  API_Call:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/API_Call.log
    encoding: utf8
    mode: w

  Fact_write:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/Fact_write.log
    encoding: utf8
    mode: w

  Embedding_write:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/Embedding_write.log
    encoding: utf8
    mode: w

  Embedding:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/Embedding.log
    encoding: utf8
    mode: w
  
  Semantic_Read:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/Semantic_Read.log
    encoding: utf8
    mode: w

  Semantic_Comparison:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/Semantic_Comparison.log
    encoding: utf8
    mode: w

  Frontend_API_Topic_Read:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/Frontend_API_Topic_Read.log
    encoding: utf8
    mode: w

loggers:
  API_Call:
    level: DEBUG
    handlers: [API_Call]
    propagate: no

  Fact_write:
    level: DEBUG 
    handlers: [Fact_write]
    propagate: no

  Embedding_write:
    level: DEBUG
    handlers: [Embedding_write]
    propagate: no

  Embedding:
    level: DEBUG
    handlers: [Embedding]
    propagate: no

  Semantic_Read:
    level: DEBUG
    handlers: [Semantic_Read]
    propagate: no
  
  Semantic_Comparison:
    level: DEBUG
    handlers: [Semantic_Comparison]
    propagate: no

  Frontend_API_Topic_Read:
    level: DEBUG
    handlers: [Frontend_API_Topic_Read]
    propagate: no
    
root:
  level: WARNING
  handlers: [console]
